package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

// TestE2EEvaluatorXml_Skeleton asserts the e2e-evaluator conductor file exists
// and carries the structural anchors this slice owns: the task id, the verbatim
// <error-reporting> reference (so TestEmbeddedCommands_ReferenceErrorReporting
// stays green — the file is NOT exempt), the BOOTSTRAP env injection, the
// never-`pkill -f` teardown rule, and the labelled SLOT comments later slices
// (execute-3 loop, execute-4 state/report) append into without renumbering.
func TestE2EEvaluatorXml_Skeleton(t *testing.T) {
	content := readEmbeddedCommand(t, "e2e-evaluator.xml")

	// Root element + identity.
	assert.Contains(t, content, `<task id="e2e-evaluator"`,
		"e2e-evaluator.xml must declare the e2e-evaluator task")

	// Shared error-reporting reference (file is not exempt — token required).
	assert.Contains(t, content, "error-reporting",
		"e2e-evaluator.xml must reference the shared error-reporting procedure")

	// BOOTSTRAP injects the orchestrator-pane contract execute-1 consumes.
	assert.Contains(t, content, "TMUX_CLI_ORCHESTRATOR_PANE",
		"BOOTSTRAP must inject TMUX_CLI_ORCHESTRATOR_PANE")

	// TEARDOWN must forbid the self-SIGTERM pkill footgun.
	assert.Contains(t, content, "pkill -f",
		"TEARDOWN must explicitly forbid pkill -f <projectname>")

	// pipe-pane log is started at BOOTSTRAP (transcript of record).
	assert.Contains(t, content, "pipe-pane",
		"BOOTSTRAP must start pipe-pane logging before any DRIVE")

	// Authored lifecycle endpoints (mine): steps 1, 1b, 2, 3, 11.
	for _, anchor := range []string{
		`n="1"`, `n="1b"`, `n="2"`, `n="3"`, `n="11"`,
	} {
		assert.Contains(t, content, anchor,
			"e2e-evaluator.xml must author step %s", anchor)
	}

	// SLOT anchors for the sibling slices so they append without renumbering.
	for _, slot := range []string{
		"SLOT steps 4", // execute-3 LOOP (DRIVE/WATCH/MEASURE/JUDGE/TRIAGE)
		"SLOT steps 8", // execute-4 STATE/REPORT/SUCCESS+RESUME
		"execute-3",    // loop slice owner labelled
		"execute-4",    // state/report slice owner labelled
	} {
		assert.Contains(t, content, slot,
			"e2e-evaluator.xml must carry the labelled slot anchor %q", slot)
	}

	// Hard driving rule: CLI/send-keys, never the tmux-cli MCP tools.
	assert.True(t,
		strings.Contains(content, "send-keys") && strings.Contains(content, "MCP"),
		"e2e-evaluator.xml must state the CLI/send-keys-not-MCP driving rule")

	// Fully-autonomous contract: the conductor must NEVER convert a mid-flow
	// decision into an operator question — not even under an "I hit limits"
	// resource-limit signal or when AskUserQuestion is unavailable in a tmux
	// worker window. This closes the operator-corrected automation defect where
	// a FAIL was handed back to the operator as an A/B/C/D question.
	assert.Contains(t, content, "FULLY AUTONOMOUS — NEVER CONVERT A DECISION INTO AN OPERATOR QUESTION",
		"e2e-evaluator.xml must carry the fully-autonomous no-operator-question mandate")
	assert.Contains(t, content, "AskUserQuestion",
		"e2e-evaluator.xml must name AskUserQuestion as a forbidden fallback")
	assert.Contains(t, content, "I hit limits",
		"e2e-evaluator.xml must state that a resource-limit signal is not a request to ask what to do")
}

// TestE2EEvaluatorMd_WrapperInstallable asserts the user-facing slash-command
// wrapper exists alongside the conductor .xml. The .md is what makes
// /tmux:e2e-evaluator INVOCABLE — WriteCommands installs the embedded .md as the
// slash command, and the .xml only holds the detailed flow the wrapper points at.
// Shipping the .xml without the .md (the original miss) leaves the command
// uninstallable even though the binary embeds and writes the .xml. director.xml /
// elaborate.xml are deliberately wrapper-less (daemon-internal), but
// e2e-evaluator is user-invoked, so its wrapper is mandatory.
func TestE2EEvaluatorMd_WrapperInstallable(t *testing.T) {
	content := readEmbeddedCommand(t, "e2e-evaluator.md")

	// YAML frontmatter description — the slash-command summary surfaced to users.
	assert.True(t, strings.HasPrefix(content, "---\n"),
		"e2e-evaluator.md must open with YAML frontmatter")
	assert.Contains(t, content, "description:",
		"e2e-evaluator.md frontmatter must carry a description")

	// Auto-generated banner — the wrapper is regenerated on every start.
	assert.Contains(t, content, "AUTO-GENERATED by tmux-cli",
		"e2e-evaluator.md must carry the auto-generated banner like its siblings")

	// The wrapper must point the invoker at the detailed conductor flow.
	assert.Contains(t, content, ".claude/commands/tmux/e2e-evaluator.xml",
		"e2e-evaluator.md must direct the agent to follow e2e-evaluator.xml")

	// Carry the two load-bearing driving rules verbatim from the .xml mandates so
	// a reader of the wrapper alone cannot miss them.
	assert.Contains(t, content, "send",
		"wrapper must restate the two-step send / CLI-drive rule")
	assert.Contains(t, content, "tmux-cli",
		"wrapper must name the tmux-cli CLI requirement")
}

// TestE2EEvaluatorXml_CycleBody asserts the execute-3 cycle-body steps drive
// the INCREMENTAL single-goal flow inside the labelled steps 4–7 SLOT: the
// self-healing loop guard, the two-step DRIVE (with the conductor pre-setting
// taskvisor.planning_mode: incremental in the target's setting.yaml), the
// incremental milestone vocabulary (discovery-done → goal-authored <id> →
// goal-<id>-done|failed → … → product-complete → app-up, heartbeat
// goal-<id>-progress), event-driven WATCH (notify-orchestrator primary /
// capture-pane fallback on 600s silence or §9 ceiling breach), per-phase
// MEASURE with p50/p90/p95 guardrails plus the per-goal incremental metrics
// (parallelism is 1 by design — never a defect signal), defect-only TRIAGE
// gated on reproduce-on-clean-retry, and the RETIRED roadmap-era preflight
// parallelism audit (step 4b repurposed, numbering held).
func TestE2EEvaluatorXml_CycleBody(t *testing.T) {
	content := readEmbeddedCommand(t, "e2e-evaluator.xml")

	// Cycle-body step anchors live inside the 4–7 slot (4b = retired preflight).
	for _, anchor := range []string{`n="4"`, `n="4b"`, `n="5"`, `n="6"`, `n="7"`} {
		assert.Contains(t, content, anchor,
			"e2e-evaluator.xml cycle body must author step %s", anchor)
	}

	// Self-healing loop guard: max 10 cycles → exhausted → escalate, stop loop.
	assert.Contains(t, content, "10 cycles",
		"cycle body must cap the self-healing loop at 10 cycles")
	assert.Contains(t, content, "exhausted",
		"loop guard must set status: exhausted past the cap")
	assert.Contains(t, content, "escalate",
		"loop guard must escalate to the human past the cap")

	// DRIVE: two-step send (buffer paste THEN a separate Enter) + readiness poll.
	assert.True(t,
		strings.Contains(content, "load-buffer") && strings.Contains(content, "paste-buffer"),
		"DRIVE must use load-buffer + paste-buffer for the text half of the send")
	assert.Contains(t, content, "❯",
		"DRIVE must readiness-poll the idle prompt before sending")

	// Incremental mode: the conductor enables one-goal-at-a-time planning in the
	// target's setting.yaml BEFORE the kickoff drives taskvisor-start (the
	// execute-1 setting seam).
	assert.Contains(t, content, "taskvisor.planning_mode: incremental",
		"DRIVE must pre-set taskvisor.planning_mode: incremental in the target")
	assert.Contains(t, content, "setting.yaml",
		"the planning-mode write targets the target's .tmux-cli/setting.yaml")

	// New incremental milestone vocabulary — kickoff, WATCH, JUDGE, glossary.
	for _, tok := range []string{
		"discovery-done",
		"goal-authored",
		"goal-&lt;id&gt;-done",
		"goal-&lt;id&gt;-progress",
		"product-complete",
		"app-up",
	} {
		assert.Contains(t, content, tok,
			"the incremental milestone vocabulary must include %q", tok)
	}

	// The roadmap-era milestone vocabulary is retired EVERYWHERE.
	for _, tok := range []string{
		"roadmap-generated",
		"preflight-passed",
		"goals-dispatched",
		"goals-done",
		"roadmap-progress",
	} {
		assert.NotContains(t, content, tok,
			"the retired roadmap milestone %q must not remain", tok)
	}

	// JUDGE fires on product-complete, backed by the daemon's marker file (the
	// execute-2/3 seam).
	assert.Contains(t, content, ".tmux-cli/taskvisor-product-complete",
		"JUDGE's product-complete trigger must name the daemon marker file")

	// WATCH: event-driven primary, capture-pane/pipe-pane fallback on silence.
	assert.Contains(t, content, "notify-orchestrator",
		"WATCH primary channel is the target's notify-orchestrator reports")
	assert.Contains(t, content, "capture-pane",
		"WATCH fallback reads capture-pane on silence")
	assert.Contains(t, content, "300s",
		"WATCH must contrast its window against the daemon's ~300s ProgressTimeoutSec")

	// MEASURE: per-phase percentile guardrails + the incremental per-goal
	// metrics; achieved parallelism is 1 by design and NEVER a defect signal.
	for _, tok := range []string{"p50", "p90", "p95", "wall-clock",
		"#goals authored", "#corrective re-scopes"} {
		assert.Contains(t, content, tok,
			"MEASURE must record the %q metric", tok)
	}
	assert.Contains(t, content, "1 by design",
		"MEASURE must state parallelism is 1 by design (not a defect signal)")
	assert.Contains(t, content, "~20-min",
		"a goal over the ~20-min right-size target is a generator signal")
	assert.Contains(t, content, "right-siz",
		"MEASURE routes oversized goals as generator right-sizing signals")

	// TRIAGE: defect-only, reproduce-on-clean-retry, signature dedupe, escalate.
	assert.Contains(t, content, "DEFECT SIGNATURE",
		"TRIAGE keys on the normalized defect signature")
	assert.Contains(t, content, "/tmux:task-report",
		"TRIAGE files /tmux:task-report for a reproduced defect")
	assert.Contains(t, content, "/tmux:task-list",
		"TRIAGE polls /tmux:task-list to resolved")
	assert.Contains(t, content, "variance",
		"TRIAGE must distinguish variance from defect")

	// The roadmap-era preflight parallelism audit is RETIRED: no DAG audit, no
	// disjoint-scope check, no concurrency-cap override (max_goals is 1 by
	// construction in incremental mode).
	for _, tok := range []string{
		"DetectOverSerialized",
		"DisjointReadySet",
		"taskvisor-concurrency",
		"max_goals=3",
	} {
		assert.NotContains(t, content, tok,
			"the retired preflight parallelism audit token %q must not remain", tok)
	}
	assert.Contains(t, content, "1 by construction",
		"step 4b must state max_goals is 1 by construction in incremental mode")

	// The shared error-reporting reference must appear EXACTLY once (execute-2
	// already added it; execute-3 must not duplicate it).
	assert.Equal(t, 1, strings.Count(content, "<error-reporting>"),
		"the <error-reporting> reference must be present exactly once (not duplicated)")
}

// TestE2EEvaluatorXml_AutoTeardownOnWedge pins the task-313 wedge wiring: the
// WATCH step treats the daemon's `goal-<id> failed` fail-fast milestone as the
// PRIMARY wedge surface, and the JUDGE/TRIAGE FAIL branch makes FAIL→TEARDOWN an
// explicit, deterministic AUTO-action (`tmux-cli e2e-teardown <session>`, no LLM
// deliberation) — the no-operator-intervention reap (AC4/AC5). The >=K / poll-error
// line count is named only as a best-effort EXTRA signal. The git-excluded .claude
// mirror, when present, must match the embedded source (dual-write).
func TestE2EEvaluatorXml_AutoTeardownOnWedge(t *testing.T) {
	content := readEmbeddedCommand(t, "e2e-evaluator.xml")

	// WATCH: the daemon fail-fast milestone is the PRIMARY, deterministic wedge
	// surface (not a 600s-silence wait).
	assert.Contains(t, content, "PRIMARY wedge surface",
		"WATCH must name goal-<id> failed as the primary wedge surface")
	assert.Contains(t, content, "goal-&lt;id&gt; failed",
		"WATCH must key on the daemon-emitted goal-<id> failed milestone")

	// TRIAGE FAIL branch: explicit AUTO-teardown, no deliberation.
	assert.Contains(t, content, "AUTO-TEARDOWN ON WEDGE",
		"FAIL branch must make teardown an explicit AUTO-action")
	assert.Contains(t, content, "tmux-cli e2e-teardown",
		"FAIL branch must run tmux-cli e2e-teardown on a wedge")
	assert.Contains(t, content, "NO LLM DELIBERATION",
		"the auto-teardown must run deterministically, without LLM deliberation")

	// Best-effort EXTRA signal wording — must NOT be load-bearing.
	assert.Contains(t, content, "&gt;=K",
		"WATCH must name the >=K identical poll-error lines as a best-effort signal")
	assert.Contains(t, content, "poll error:",
		"WATCH must reference the daemon's poll error: lines as the extra signal")

	// The 600s silence window is preserved as the BACKSTOP (never lowered/removed).
	assert.Contains(t, content, "600s",
		"the 600s WATCH silence window must remain the backstop")
	assert.Contains(t, content, "BACKSTOP",
		"600s-silence / ceiling-breach must be reframed as the backstop, not the primary")

	// Dual-write: the git-excluded .claude mirror, when present in this checkout,
	// must be byte-identical to the embedded source. Skipped where .claude was not
	// regenerated (fresh checkout / CI) — the `diff` verification step covers it
	// there; readEmbeddedCommand already proves the embedded source of truth.
	if root := findRepoRoot(); root != "" {
		mirror := filepath.Join(root, ".claude", "commands", "tmux", "e2e-evaluator.xml")
		if b, err := os.ReadFile(mirror); err == nil {
			assert.Equal(t, content, string(b),
				".claude mirror must match the embedded e2e-evaluator.xml (dual-write)")
		}
	}
}

// findRepoRoot walks up from the test's working directory to the directory that
// holds a .claude/commands/tmux tree, returning "" if none is found. Best-effort:
// the on-disk .claude copy is git-excluded and may be absent.
func findRepoRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		return ""
	}
	for {
		if fi, err := os.Stat(filepath.Join(dir, ".claude", "commands", "tmux")); err == nil && fi.IsDir() {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}
