package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/console/tmux-cli/internal/setup"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// The /tmux:supervisor:fresh slice (docs/architecture/supervisor-fresh-design.md
// §5a). The command is dir-namespaced: embedded/commands/tmux/supervisor/fresh.md
// installs to .claude/commands/tmux/supervisor/fresh.md, which Claude Code
// surfaces as /tmux:supervisor:fresh (precedent: worker/execute.md →
// /tmux:worker:execute).
//
// These are embed/content assertions only — no tmux server, no filesystem state
// outside t.TempDir(), per the AGENTS.md "tests must pass without a running
// tmux server" constraint.

const (
	freshMdRel  = "supervisor/fresh.md"
	freshXMLRel = "supervisor/fresh.xml"
)

// TestSupervisorFreshCmd_EmbeddedFilesExist asserts both halves of the command
// ship in the embedded FS. `//go:embed embedded/commands/tmux` (session.go:49)
// has NO `all:` prefix, so a name beginning with '_' or '.' would be silently
// dropped — these reads are the guard that the pair actually made it in.
func TestSupervisorFreshCmd_EmbeddedFilesExist(t *testing.T) {
	for _, rel := range []string{freshMdRel, freshXMLRel} {
		content := readEmbeddedCommand(t, rel)
		assert.NotEmpty(t, strings.TrimSpace(content),
			"%s must be embedded and non-empty", rel)
	}
}

// TestSupervisorFreshMd_Entry asserts the .md entry follows the sibling entry
// convention (frontmatter description + generated banner) and delegates to its
// .xml procedure rather than improvising the flow inline.
func TestSupervisorFreshMd_Entry(t *testing.T) {
	content := readEmbeddedCommand(t, freshMdRel)

	assert.True(t, strings.HasPrefix(content, "---\n"),
		"fresh.md must open with YAML frontmatter (sibling entry convention)")
	assert.Contains(t, content, "description:",
		"fresh.md frontmatter must carry a description")
	assert.Contains(t, content, "AUTO-GENERATED by tmux-cli",
		"fresh.md must carry the do-not-hand-edit banner")

	// Delegates to the installed procedure path, not the embedded source path.
	assert.Contains(t, content, ".claude/commands/tmux/supervisor/fresh.xml",
		"fresh.md must point at its installed .xml procedure")
}

// TestSupervisorFreshXml_Contract asserts fresh.xml authors the §5a procedure
// and the §4 handoff contract with BYTE-EXACT tokens. The Stop-hook slice
// (tmux-supervisor-cycle.sh) and the supervisor.xml step-9b slice assert the
// SAME strings from the other side of the contract, so a rename here without a
// rename there silently breaks the handoff.
func TestSupervisorFreshXml_Contract(t *testing.T) {
	content := readEmbeddedCommand(t, freshXMLRel)

	assert.Contains(t, content, `<task id="supervisor-fresh"`,
		"fresh.xml must declare the supervisor-fresh task")

	// §4 marker path + YAML fields — byte-exact, cross-slice contract.
	assert.Contains(t, content, ".tmux-cli/fresh-handoff",
		"fresh.xml must name the marker path exactly")
	for _, field := range []string{"plan:", "self_wave:", "cycle:", "requested_by:", "created:"} {
		assert.Contains(t, content, field,
			"fresh.xml must author the %q marker field", field)
	}

	// §5a.2 guards — the daemon/recurring driver owns dispatch there.
	assert.Contains(t, content, "taskvisor-active",
		"fresh.xml must refuse under the taskvisor-active guard")
	assert.Contains(t, content, "recurring-active",
		"fresh.xml must refuse under the recurring-active guard")

	// §5a.2 window guard — the hook only acts on the bare `supervisor` window,
	// so arming anywhere else strands the marker.
	assert.Contains(t, content, "TMUX_WINDOW_UUID",
		"fresh.xml must resolve its own window (hook-identical UUID lookup)")

	// §5a.4 atomic write — never a half-written marker the hook could parse.
	assert.Contains(t, content, "rename",
		"fresh.xml must mandate the temp+rename atomic write")

	// §5a.4 the one-line confirmation, and §5a.5 the hard stop.
	assert.Contains(t, content, "FRESH HANDOFF armed",
		"fresh.xml must print the armed confirmation line")
	assert.Contains(t, content, "STOP",
		"fresh.xml must STOP — the Stop hook performs the restart")

	// Shared error-reporting reference: fresh.xml is NOT on the
	// exemptFromErrorReporting allow-list, so TestEmbeddedCommands_ReferenceErrorReporting
	// requires this token. Asserted here too so a regression names the cause.
	assert.Contains(t, content, "error-reporting",
		"fresh.xml must reference the shared error-reporting procedure")
}

// TestSupervisorFreshXml_ValidatesBeforeArming asserts the §5a.1 ordering
// invariant: a marker is NEVER written for a plan file that is missing or
// empty. The hook consumes the marker before sending, so a marker pointing at
// nothing costs a real restart cycle.
func TestSupervisorFreshXml_ValidatesBeforeArming(t *testing.T) {
	content := readEmbeddedCommand(t, freshXMLRel)

	assert.Contains(t, content, "$ARGUMENTS",
		"fresh.xml must validate its $ARGUMENTS")
	assert.Contains(t, content, "non-empty",
		"fresh.xml must require the plan file be non-empty")

	// The loud-usage-error branch must precede the marker-write step, so no
	// ordering slip can arm a marker on a bad argument. Scoped to <flow>: the
	// <output> preamble legitimately names the confirmation line up top, which
	// is documentation, not the executed step.
	flowStart := strings.Index(content, "<flow>")
	flowEnd := strings.Index(content, "</flow>")
	require.NotEqual(t, -1, flowStart, "fresh.xml must author a <flow>")
	require.Greater(t, flowEnd, flowStart, "fresh.xml <flow> must be well-formed")
	flow := content[flowStart:flowEnd]

	usageIdx := strings.Index(flow, "USAGE:")
	require.NotEqual(t, -1, usageIdx, "fresh.xml <flow> must emit a loud usage error")
	markerIdx := strings.Index(flow, "fresh-handoff\"")
	require.NotEqual(t, -1, markerIdx, "fresh.xml <flow> must rename onto the marker path")
	assert.Less(t, usageIdx, markerIdx,
		"the usage-error branch must be authored BEFORE the marker-write step")
}

// TestSupervisorFreshCmd_InstallWalkHandlesFileAndDirSibling is the install-
// mechanism verification the task calls for: `supervisor/` now sits NEXT TO
// supervisor.md/supervisor.xml. buildCommandTemplates (session.go:1499) keys
// its map on the slash-joined relative path and WriteCommands
// (internal/setup/commands.go) MkdirAll's each entry's parent, so the file and
// the dir of the same stem coexist. cr-apply-fixes already has this exact shape
// (cr-apply-fixes.md + cr-apply-fixes.xml + cr-apply-fixes/), which is the
// precedent this asserts alongside.
func TestSupervisorFreshCmd_InstallWalkHandlesFileAndDirSibling(t *testing.T) {
	templates := buildCommandTemplates()

	// The walk yields both the dir-namespaced pair and the same-stem siblings.
	for _, rel := range []string{
		freshMdRel, freshXMLRel, // supervisor/ subdir
		"supervisor.md", "supervisor.xml", // same-stem sibling FILES
		"cr-apply-fixes.xml", "cr-apply-fixes/stage-1-detect.xml", // precedent shape
		"worker/execute.md", // dir-namespacing precedent
	} {
		require.Contains(t, templates, rel,
			"buildCommandTemplates must walk %s into the install map", rel)
		assert.NotEmpty(t, templates[rel], "%s must carry content", rel)
	}

	// Keys are slash-separated relative paths (not OS-separated, not absolute) —
	// WriteCommands joins them onto .claude/commands/tmux/.
	assert.Equal(t, "supervisor/fresh.xml", freshXMLRel)
	assert.NotContains(t, templates[freshXMLRel], "\x00")

	// Full install round-trip into a temp project root.
	root := t.TempDir()
	require.NoError(t, setup.WriteCommands(root, templates))

	tmuxDir := filepath.Join(root, ".claude", "commands", "tmux")

	// The subdir pair landed at the path that yields /tmux:supervisor:fresh.
	for _, rel := range []string{freshMdRel, freshXMLRel} {
		got, err := os.ReadFile(filepath.Join(tmuxDir, filepath.FromSlash(rel)))
		require.NoError(t, err, "%s must be installed on disk", rel)
		assert.Equal(t, templates[rel], string(got),
			"%s content must survive the install verbatim", rel)
	}

	// The same-stem FILE siblings survived the dir creation (and vice versa) —
	// the actual regression this test exists to catch.
	for _, rel := range []string{"supervisor.md", "supervisor.xml"} {
		info, err := os.Stat(filepath.Join(tmuxDir, rel))
		require.NoError(t, err, "%s must still install next to the supervisor/ dir", rel)
		assert.False(t, info.IsDir(), "%s must be a file, not shadowed by the dir", rel)
	}

	supDir, err := os.Stat(filepath.Join(tmuxDir, "supervisor"))
	require.NoError(t, err, "supervisor/ dir must be created")
	assert.True(t, supDir.IsDir(), "supervisor must be a directory")
}
